# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Final' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final
  pod 'DateToolsSwift'

  target 'FinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
